sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJYLFRgMMzvYoT7BC3L
    access-key-secret: eju2kW5HBvNGvpQGC2qFQzB3BWeBUO
    bucket-name: sky-mirrorseek

  redis:
    host: localhost
    port: 6379
    database: 0

  wechat:
    appid: wxb0ea489a37fcb228
    secret: ae0636711cb7154ead78010dd86fbab0
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
